# Generated by Django 6.1.1 on 2026-09-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.bag'),
        ),
    ]
