# Generated by Django 6.1.1 on 2026-09-17 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_bag_description_alter_cartitem_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='image',
        ),
        migrations.CreateModel(
            name='BagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.bag')),
            ],
        ),
    ]
