# Generated by Django 6.1.1 on 2026-09-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address_order_city_order_full_name_order_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
