# Generated by Django 6.1.1 on 2026-09-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bags', to='store.category'),
        ),
    ]
