# Generated by Django 6.1.1 on 2026-10-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_bag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bag',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
