# Generated by Django 6.1.1 on 2026-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_bag_homepage_order_bag_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, help_text='Where this bag appears on the homepage: 1 is first, 2 is second, and so on. The homepage shows at most 12 bags, in this order.', verbose_name='homepage position'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Tick to feature this bag on the homepage. A new bag is never featured automatically.', verbose_name='show on homepage'),
        ),
    ]
