# Generated by Django 6.1.1 on 2026-10-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_stock_restored'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField()),
                ('visitor', models.CharField(max_length=16)),
                ('kind', models.CharField(choices=[('page', 'Page view'), ('cart', 'Added to cart')], max_length=8)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('bag_id', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, max_length=80)),
                ('results', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('device', models.CharField(blank=True, max_length=10)),
                ('os', models.CharField(blank=True, max_length=12)),
                ('browser', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'verbose_name': 'visitor event',
                'verbose_name_plural': 'visitor analytics',
                'indexes': [models.Index(fields=['kind', 'day'], name='store_visit_kind_892e4c_idx'), models.Index(fields=['bag_id', 'kind'], name='store_visit_bag_id_0fc76a_idx')],
            },
        ),
    ]
