# Generated by Django 6.1.2 on 2026-10-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_visitevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('NOT_CALCULATED', 'Not calculated (earlier order)'), ('CALCULATED', 'Calculated'), ('QUOTE_REQUIRED', 'Too far for a set fee: quote needed'), ('UNVERIFIED', 'Address not verified: confirm fee'), ('AGREED', 'Fee agreed by phone')], db_default='NOT_CALCULATED', default='NOT_CALCULATED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
