"""
Django settings for bagstore_config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# With no DEBUG setting, debug is on only where a .env file exists (your own
# computer) and off everywhere else (Render has no .env file). On Render, set
# DEBUG=False anyway.
DEBUG = config("DEBUG", default=(BASE_DIR / ".env").exists(), cast=bool)

SECURE_SSL_REDIRECT = not DEBUG

SESSION_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_SECURE = not DEBUG

SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0

SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG

SECURE_HSTS_PRELOAD = not DEBUG

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# /healthz/ answers "ok" and nothing else, so it may be asked over plain http
# (Render's own health check, an uptime monitor) without being redirected.
SECURE_REDIRECT_EXEMPT = [r"^healthz/$"]


ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost"
).split(",")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config(
        "CSRF_TRUSTED_ORIGINS",
        default=""
    ).split(",")
    if origin.strip()
]

# Render sets RENDER_EXTERNAL_HOSTNAME (for example your-app.onrender.com) on
# every web service, so that address always works as well as your own domain.
RENDER_EXTERNAL_HOSTNAME = config("RENDER_EXTERNAL_HOSTNAME", default="")

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'store',
    "cloudinary",
    "cloudinary_storage",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "store.middleware.CanonicalHostMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "store.middleware.PrivatePagesMiddleware",
]

# The shop's one proper address, for search engines and shared links, for
# example https://bagsnbeyond.com (leave empty and the address of each request
# is used).
SITE_URL = config("SITE_URL", default="").rstrip("/")

# If set (for example bagsnbeyond.com), anyone arriving by another address, such
# as your-app.onrender.com or www., is sent to this one for good.
CANONICAL_HOST = config("CANONICAL_HOST", default="")

# The codes Google Search Console and Bing Webmaster Tools give you to prove the
# site is yours (the "content" of their meta tag).
GOOGLE_SITE_VERIFICATION = config("GOOGLE_SITE_VERIFICATION", default="")
BING_SITE_VERIFICATION = config("BING_SITE_VERIFICATION", default="")

ROOT_URLCONF = 'bagstore_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.store_globals',
            ],
        },
    },
]

WSGI_APPLICATION = 'bagstore_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Neon puts an idle database to sleep and then drops its connections. So a
# connection is kept for only 60 seconds (set DB_CONN_MAX_AGE to change that),
# and Django checks that a kept connection is still alive before using it
# (CONN_HEALTH_CHECKS), opening a new one if Neon closed it.
DATABASES = {
    "default": dj_database_url.parse(
        config("DATABASE_URL"),
        conn_max_age=config("DB_CONN_MAX_AGE", default=60, cast=int),
        conn_health_checks=True,
        disable_server_side_cursors=True,    # needed by Neon's pooled connection
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT=BASE_DIR/"staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files uploaded by users
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": config("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": config("CLOUDINARY_API_KEY"),
    "API_SECRET": config("CLOUDINARY_API_SECRET"),
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Emails go out through Brevo, one of two ways:
#   - BREVO_API_KEY set: over HTTPS. This works on Render's free plan, which
#     blocks the SMTP ports.
#   - otherwise: over SMTP, as before (needs a paid Render plan, or your own
#     computer).
BREVO_API_KEY = config("BREVO_API_KEY", default="")

if BREVO_API_KEY:
    EMAIL_BACKEND = "store.brevo_backend.BrevoEmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

    EMAIL_HOST = config("EMAIL_HOST")
    EMAIL_PORT = config("EMAIL_PORT", cast=int)
    EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)

    EMAIL_HOST_USER = config("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

EMAIL_TIMEOUT = 5

# Where the "NEW BAG STORE ORDER" alert goes. Set ORDER_NOTIFICATION_EMAIL to
# change it without touching the code.
ORDER_NOTIFICATION_EMAIL = config(
    "ORDER_NOTIFICATION_EMAIL", default="jossenndiwalana@gmail.com"
)

# Authentication
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "EMAIL_AUTHENTICATION": True,
        "EMAIL_AUTHENTICATION_AUTO_CONNECT": True,
    },
}

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1', 'password2']


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------
# Customers log in at /login/ with their e-mail address. ModelBackend stays
# so the Django admin keeps working with usernames.
AUTHENTICATION_BACKENDS = [
    "store.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# django-allauth is used only for "Continue with Google". These keep that flow
# consistent with the shop (username == e-mail, the shop's own messages, and a
# redirect to /login/ instead of an error page when Google sign-in fails).
ACCOUNT_ADAPTER = "store.adapters.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "store.adapters.SocialAccountAdapter"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "WARNING"},
}